services:
  - type: web
    name: canvas-mcp-server
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: node build/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CANVAS_API_TOKEN
        sync: false
      - key: CANVAS_DOMAIN
        sync: false
      - key: MCP_API_KEY
        sync: false
        generateValue: true
      - key: CANVAS_MAX_RETRIES
        value: 3
      - key: CANVAS_RETRY_DELAY
        value: 1000
      - key: CANVAS_TIMEOUT
        value: 30000
      - key: LOG_LEVEL
        value: info

